import Footer from "@/components/Shared/Footer";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import BackToTop from "@/components/Shared/BackToTop";
export const metadata = {
  title: "DND Task Management",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container min-h-screen px-5 mx-auto text-white">
          {children}
        </main>
        <Footer />
        <BackToTop />
      </body>
    </html>
  );
}
